modulesync 4.0.0
voxpupuli/puppet-cassandra pull request #468
Opened 2020-11-25 16:02 UTC by bastelfreak

modulesync 4.0.0

2020-11-25 18:16 UTC, ekohl requested changes
Acceptance tests need to be updated to use voxpupuli-acceptance. Previously they didn't run at all so who knows what dragons are currently sleeping there.

2021-12-16 09:40 UTC, ekohl commented on spec/acceptance/cassandra_spec.rb
> +        expect(subject).to be_running
Why is this better? We use `is_expected` pretty much everywhere and if Rubocop enforces this new style, I'd be in favor of disabling that cop (unless there's a very good reason).

2021-12-16 09:56 UTC, bastelfreak commented
I did a rough cleanup but more work needs to be put into it. I'm not sure if it's worth doing it. I'm not a cassandra expert and the latest release, from 2020-09-18 only has ~3000 downloads on the forge. maybe we just archive the repository.

2021-12-16 10:57 UTC, ekohl commented on manifests/params.pp
>          '18.04': {
This looks like it should be default. `openjdk-7-jre-headless` didn't exist in Stretch (oldoldstable) so unlikely to exist in anything newer. On the other hand, version 8 is only in Stretch and Buster appears to only have version 11.

2021-12-16 11:09 UTC, ekohl commented
I'd be in favor of archiving this.

2024-02-08 23:36 UTC, zilchms commented
since there has been some disagreement if this should be retired on the IRC, i am going to have a look at the msync pr and try to fix this whole module up

2025-08-15 09:43 UTC, closed without merging